# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

1.14.3


#### 3. Create a null vector of size 10 (★☆☆)

In [14]:
v_0 = np.zeros(10)
v_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [15]:
v_0.size * v_0.itemsize

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [22]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [23]:
v_null = np.zeros(10)
v_null[4] += 1
v_null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [18]:
v2 = np.arange(10, 50)
v2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [22]:
v2[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
m1 = np.array(np.arange(0,9)).reshape((3,3))
m1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [42]:
x = np.array([1,2,0,0,4,0])
for index, el in np.ndenumerate(x):
    if (el != 0):
        print(index[0])

0
1
4


#### 11. Create a 3x3 identity matrix (★☆☆)

In [9]:
id_mat = np.zeros((3,3))
np.fill_diagonal(id_mat, 1)
id_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
ar1 = np.random.random(size = (3,3,3))
ar1

array([[[0.14886224, 0.60568523, 0.73157127],
        [0.17890915, 0.96781927, 0.26106013],
        [0.50523555, 0.32114145, 0.25074249]],

       [[0.2742204 , 0.1550285 , 0.15810383],
        [0.4801731 , 0.14532772, 0.44144486],
        [0.48584451, 0.79684212, 0.77016261]],

       [[0.75637444, 0.55069913, 0.42920986],
        [0.32336134, 0.37685021, 0.87685495],
        [0.85126808, 0.47505025, 0.58426196]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
ar2 = np.random.random(size=(10,10))
print(ar2.min())
print(ar2.max())

7.120303385799165e-05
0.9874089675877962


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [21]:
v_rand = np.random.randint(0,high = 100, size=30)
v_rand.mean()

43.8

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [27]:
a = np.zeros((3,3))
a = np.pad(a, pad_width=1, mode='constant', constant_values=1)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [28]:
np.pad(a, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan = nan
np.nan == np.nan  False
np.inf > np.nan False
np.nan - np.nan nan
0.3 == 3 * 0.1 False!!!
```

In [33]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [49]:
m5 = np.zeros((5,5))
for index, el in np.ndenumerate(m5):
    if (index[0] == index[1] + 1):
        m5[index] = index[0]
m5

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [57]:
m6 = np.zeros((8,8))
for index, el in np.ndenumerate(m6):
    m6[index] = (index[0] + index[1] + 1) % 2 
m6


array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [65]:
a_20 = np.random.random((6,7,8))
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [3]:
a_21 = np.array([[1,0],[0,1]])
np.tile(a_21, (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [9]:
a_22 = np.random.randint(-100, 100, (5,5))
res_22 = a_22 / np.linalg.norm(a_22, axis=-1)[:, np.newaxis]
print(a_22)
print('\n')
print(res_22)

[[-65 -56 -46  -9 -93]
 [-22  33 -98  -9 -64]
 [ 89  45 -52 -59  53]
 [-90  -9  93 -69 -25]
 [-36 -51  56 -18 -23]]


[[-0.48171943 -0.41501981 -0.34090913 -0.06669961 -0.68922933]
 [-0.17754642  0.26631963 -0.79088859 -0.07263263 -0.51649867]
 [ 0.64669577  0.32698101 -0.37784472 -0.42870843  0.38511096]
 [-0.6038229  -0.06038229  0.62395032 -0.46293089 -0.16772858]
 [-0.40539101 -0.57430393  0.63060824 -0.20269551 -0.25899981]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [16]:
c_RGBA = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [11]:
m24_1 = np.random.randint(0, 100, (5, 3))
m24_2 = np.random.randint(0, 100, (3, 2))
res_24 = m24_1.dot(m24_2)
print(res_24)

[[ 2314  6214]
 [12672  1239]
 [ 8953  4262]
 [12395  3169]
 [ 8151  5876]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [17]:
a_25 = np.array([0, 2, 3, 3.1, 4, 6, 10, 11])
a_25[(a_25 > 3) & (a_25 < 8)] *= -1
a_25

array([ 0. ,  2. ,  3. , -3.1, -4. , -6. , 10. , 11. ])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [18]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1)) 
# don't understand why

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [9]:
Z = np.array(range(8))
print(Z)
#print(Z**Z) # legal
#print(2 << Z >> 2) 
#print(Z <- Z) # out: [False False False False False False False False]
#print(1j*Z) # out: [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j]
#print(Z/1/1) # legal
#print(Z<Z>Z) # gives error

[0 1 2 3 4 5 6 7]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [33]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [22]:
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 3])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
defaults = np.seterr(all="ignore")
a_25[2] / 0

inf

In [32]:
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [35]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2018-05-19
Today:  2018-05-20
Tomorrow:  2018-05-21


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [11]:
np.arange('2016-07-01', '2016-08-01', dtype='datetime64')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [36]:
A = np.zeros(3) + 9
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-49.5, -49.5, -49.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
a_37 = np.zeros((5,5))
a_37 += range(0,5)
a_37

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [20]:
v_40 = np.random.random(10)
print('Old \n {} '.format(v_40))
v_40.sort()
print('New \n {} '.format(v_40))

Old 
 [0.44370988 0.60296946 0.82647386 0.30902091 0.7704412  0.79190175
 0.64186204 0.83130574 0.48224023 0.14418766] 
New 
 [0.14418766 0.30902091 0.44370988 0.48224023 0.60296946 0.64186204
 0.7704412  0.79190175 0.82647386 0.83130574] 


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)